In [106]:
import numpy as np
import pandas as pd
import sqlite3
import regex as re

In [27]:
con = sqlite3.connect("database")
cur = con.cursor()
cur.execute("SELECT * FROM movie_titles")
res = cur.fetchall()
res

[(1, 1950, 'Hindi', 'Sangram', 1),
 (2, 1950, 'Hindi', 'Raj Mukut', 1),
 (3, 1950, 'Hindi', 'Beqasoor', 1),
 (4, 1950, 'Hindi', 'Hamara Ghar', 1),
 (5, 1950, 'Hindi', 'Gulnar', 1),
 (6, 1950, 'Hindi', 'Samadhi', 1),
 (7, 1950, 'Hindi', 'Sartaj', 1),
 (8, 1950, 'Hindi', 'Dilruba', 1),
 (9, 1950, 'Hindi', 'Wafa', 1),
 (10, 1950, 'Hindi', 'Gauna', 1),
 (11, 1950, 'Hindi', 'Banwra', 1),
 (12, 1950, 'Hindi', 'Rangila Musafir', 1),
 (13, 1950, 'Hindi', 'Khiladi', 1),
 (14, 1950, 'Hindi', 'Dastan', 1),
 (15, 1950, 'Hindi', 'Lajawab', 1),
 (16, 1950, 'Hindi', 'Sachcha Pyaar', 1),
 (17, 1950, 'Hindi', 'Arzoo', 1),
 (18, 1950, 'Hindi', 'Chor', 1),
 (19, 1950, 'Hindi', 'Bhai Bahen', 1),
 (20, 1950, 'Hindi', 'Shri Ganesh Mahima', 1),
 (21, 1950, 'Hindi', 'Rupaiya', 1),
 (22, 1950, 'Hindi', 'Har Har Mahadev', 1),
 (23, 1950, 'Hindi', 'Magroor', 1),
 (24, 1950, 'Hindi', 'Dahej', 1),
 (25, 1950, 'Hindi', 'Dolti Naiya', 1),
 (26, 1950, 'Hindi', 'Putli', 1),
 (27, 1950, 'Hindi', 'Babul', 1),
 (28, 1950, 'Hindi', 'Jogan', 1),
 (29, 1950, 'Hindi', 'Sati Narmada', 1),
 (30, 1950, 'Hindi', 'Sargam', 1),
 (31, 1950, 'Hindi', 'Nishana', 1),
 (32, 1950, 'Hindi', 'Afsar', 1),
 (33, 1950, 'Hindi', 'Nirala', 1),
 (34, 1950, 'Hindi', 'Pardes', 1),
 (35, 1950, 'Hindi', 'Jodidar', 1),
 (36, 1950, 'Hindi', 'Pyaar Ki Manzil', 1),
 (37, 1950, 'Hindi', 'Jan Pahchan', 1),
 (38, 1950, 'Hindi', 'Pehla Aadmi', 1),
 (39, 1950, 'Hindi', 'Meri Asha', 1),
 (40, 1950, 'Hindi', 'Veer Babruwahan', 1),
 (41, 1950, 'Hindi', 'Bhagwan Shri Krishna', 1),
 (42, 1950, 'Hindi', 'Meena Bazaar', 1),
 (43, 1950, 'Hindi', 'Hamari Beti', 1),
 (44, 1950, 'Hindi', 'Nai Bhabhi', 1),
 (45, 1950, 'Hindi', 'Shadi Ki Raat', 1),
 (46, 1950, 'Hindi', 'Muqaddar', 1),
 (47, 1950, 'Hindi', 'Shaan', 1),
 (48, 1950, 'Hindi', 'Chhoti Bhabi', 1),
 (49, 1950, 'Hindi', 'Alakh Niranjan', 1),
 (50, 1950, 'Hindi', 'Man Ka Meet', 1),
 (51, 1950, 'Hindi', 'Aahuti', 1),
 (52, 1950, 'Hindi', 'Bhishma Pratigya', 1),
 (53, 1950, 'Hindi', 'Kisi Ki Yaad', 1),
 (54, 1950, 'Hindi', 'Sabak', 1),
 (55, 1950, 'Hindi', 'Bahurani', 1),
 (56, 1950, 'Hindi', 'Ram Darshan', 1),
 (57, 1950, 'Hindi', 'Raj Rani', 1),
 (58, 1950, 'Hindi', 'Nirdosh', 1),
 (59, 1950, 'Hindi', 'Anmol Ratan', 1),
 (60, 1950, 'Hindi', 'Shri Krishna Darshan', 1),
 (61, 1950, 'Hindi', 'Madhubala', 1),
 (62, 1950, 'Hindi', 'Mashaal', 1),
 (63, 1950, 'Hindi', 'Khamosh Sipahi', 1),
 (64, 1950, 'Hindi', 'Circuswale', 1),
 (65, 1950, 'Hindi', 'Meharbani', 1),
 (66, 1950, 'Hindi', 'Aankhen', 1),
 (67, 1950, 'Hindi', 'Bakhshish', 1),
 (68, 1950, 'Hindi', 'Janmashtami', 1),
 (69, 1950, 'Hindi', 'Hanste Rehna', 1),
 (70, 1950, 'Hindi', 'Bawre Nain', 1),
 (71, 1950, 'Hindi', 'Achchaji', 1),
 (72, 1950, 'Hindi', 'Khel', 1),
 (73, 1950, 'Hindi', 'Pagle', 1),
 (74, 1950, 'Hindi', 'Lavangi', 1),
 (75, 1950, 'Hindi', 'Basera', 1),
 (76, 1950, 'Hindi', 'Biwi', 1),
 (77, 1950, 'Hindi', 'Jalte Deep', 1),
 (78, 1950, 'Hindi', 'Nili', 1),
 (79, 1950, 'Hindi', 'Sheesh Mahal', 1),
 (80, 1950, 'Hindi', 'Kamal Ke Phool', 1),
 (81, 1950, 'Hindi', 'Veer Bhimsen', 1),
 (82, 1950, 'Hindi', 'Babooji', 1),
 (83, 1950, 'Hindi', 'Hindustan Hamara', 1),
 (84, 1950, 'Hindi', 'Bebus', 1),
 (85, 1950, 'Hindi', 'Birha Ki Raat', 1),
 (86, 1950, 'Hindi', 'Hanste Aansoo', 1),
 (87, 1950, 'Hindi', 'Surajmukhi', 1),
 (88, 1950, 'Hindi', 'Aflatoon', 1),
 (89, 1950, 'Hindi', 'Sangeeta', 1),
 (90, 1950, 'Hindi', 'Shri Ram Avtar', 1),
 (91, 1950, 'Hindi', 'Pyar', 1),
 (92, 1950, 'Hindi', 'Aadhi Raat', 1),
 (93, 1950, 'British', 'Her Favourite Husband', 2),
 (94, 1950, 'British', 'State Secret', 2),
 (95, 1950, 'British', 'She Shall Have Murder', 2),
 (96, 1950, 'British', 'Into the Blue', 2),
 (97, 1950, 'British', 'Madeleine', 2),
 (98, 1950, 'British', 'Lilli Marlene', 2),
 (99, 1950, 'British', "Hangman's Wharf", 2),
 (100, 1950, 'British', 'Someone at the Door', 2),
 (101, 1950, 'British', 'Portrait of Clare', 2),
 (102, 1950, 'British', 'The Gorbals Story', 2),
 (103, 1950, 'British', "The Girl Who Couldn't Quite", 2),
 (104, 1950, 'British', 'Black Jack', 2),
 (105, 1950, 'British', 'Dangerous Assignment', 2),
 (106, 1950, 'British', 'The Wooden Horse', 2),
 (107, 1950, 'British', 'Morning Departure', 2),
 (108, 1950, 'British', 'Shadow of the Past', 2),
 (109, 1950, 'British', 'Midnight Episode', 2),
 (110, 1950, 'British', 'The Kangaroo Kid', 2),
 (111, 1950, 'British', 'Old Mother Riley Headmistress', 2),
 (112, 1950, 'British', 'Treasure Island', 2),
 (113, 1950, 'British', 'Soho Conspiracy', 2),
 (114, 1950, 'British', 'Night and the City', 2),
 (115, 1950, 'British', 'The Woman with No Name', 2),
 (116, 1950, 'British', 'Highly Dangerous', 2),
 (117, 1950, 'British', 'Trio', 2),
 (118, 1950, 'British', 'The Second Mate', 2),
 (119, 1950, 'British', 'Waterfront', 2),
 (120, 1950, 'British', 'Chance of a Lifetime', 2),
 (121, 1950, 'British', 'The Elusive Pimpernel', 2),
 (122, 1950, 'British', 'Dick Barton at Bay', 2),
 (123, 1950, 'British', 'The Mudlark', 2),
 (124, 1950, 'British', 'The Body Said No!', 2),
 (125, 1950, 'British', "Let's Have a Murder", 2),
 (126, 1950, 'British', 'Gone to Earth', 2),
 (127, 1950, 'British', 'Seven Days to Noon', 2),
 (128, 1950, 'British', 'The Astonished Heart', 2),
 (129, 1950, 'British', '1950', 2),
 (130, 1950, 'British', 'Prelude to Fame', 2),
 (131, 1950, 'British', 'The Lady Craved Excitement', 2),
 (132, 1950, 'British', 'Bitter Springs', 2),
 (133, 1950, 'British', 'The Clouded Yellow', 2),
 (134, 1950, 'British', 'Last Holiday', 2),
 (135, 1950, 'British', 'The Black Rose', 2),
 (136, 1950, 'British', 'Double Confession', 2),
 (137, 1950, 'British', 'So Long at the Fair', 2),
 (138, 1950, 'British', 'Dark Interval', 2),
 (139, 1950, 'British', 'Tony Draws a Horse', 2),
 (140, 1950, 'British', 'No Trace', 2),
 (141, 1950, 'British', 'The Magnet', 2),
 (142, 1950, 'British', 'The Twenty Questions Murder Mystery', 2),
 (143, 1950, 'British', 'Shadow of the Eagle', 2),
 (144, 1950, 'British', 'Your Witness', 2),
 (145, 1950, 'British', 'What the Butler Saw', 2),
 (146, 1950, 'British', 'Torment', 2),
 (147, 1950, 'British', 'The Reluctant Widow', 2),
 (148, 1950, 'British', 'Blackout', 2),
 (149, 1950, 'British', 'The Fall of the House of Usher', 2),
 (150, 1950, 'British', 'Four Men in Prison', 2),
 (151, 1950, 'British', 'Bait', 2),
 (152, 1950, 'British', 'Murder Without Crime', 2),
 (153, 1950, 'British', 'The Naked Heart', 2),
 (154, 1950, 'British', 'Something in the City', 2),
 (155, 1950, 'British', 'Dance Hall', 2),
 (156, 1950, 'British', 'Come Dance with Me', 2),
 (157, 1950, 'British', 'The Angel with the Trumpet', 2),
 (158, 1950, 'British', 'The Dancing Years', 2),
 (159, 1950, 'British', 'The Happiest Days of Your Life', 2),
 (160, 1950, 'British', 'Odette', 2),
 (161, 1950, 'British', 'Cairo Road', 2),
 (162, 1950, 'British', 'The Girl Is Mine', 2),
 (163, 1950, 'British', 'No Place for Jennifer', 2),
 (164, 1950, 'British', 'The Blue Lamp', 2),
 (165, 1950, 'British', 'Guilt Is My Shadow', 2),
 (166, 1950, 'British', 'The Woman in Question', 2),
 (167, 1950, 'British', 'The Dragon of Pendragon Castle', 2),
 (168, 1950, 'British', 'Stage Fright', 2),
 (169, 1950, 'British', 'Over the Garden Wall', 2),
 (170, 1950, 'British', 'Cage of Gold', 2),
 (171, 1950, 'British', 'My Daughter Joy', 2),
 (172, 1950, 'British', "Don't Say Die", 2),
 (173, 1950, 'British', 'Once a Sinner', 2),
 (174, 1950, 'British', 'Golden Salamander', 2),
 (175, 1950, 'British', "Paul Temple's Triumph", 2),
 (176, 1950, 'British', 'Room to Let', 2),
 (177, 1950, 'British', 'Up for the Cup', 2),
 (178, 1950, 'British', 'They Were Not Divided', 2),
 (179, 1950, 'Telugu', 'Apoorva Sahodarulu (Dubbed from Tamil)', 3),
 (180, 1950, 'Telugu', 'Jeevitham', 3),
 (181, 1950, 'Telugu', 'Modhati Rathri', 3),
 (182, 1950, 'Telugu', 'Maaya Rambha', 3),
 (183, 1950, 'Telugu', 'Paramanandayya Sishyulu', 3),
 (184, 1950, 'Telugu', 'Adhrusta Deepudu', 3),
 (185, 1950, 'Telugu', 'Beedala Patlu', 3),
 (186, 1950, 'Telugu', 'Lakshmamma', 3),
 (187, 1950, 'Telugu', 'Samsaram', 3),
 (188, 1950, 'Telugu', 'Thirugubatu', 3),
 (189, 1950, 'Telugu', 'Sri Lakshmamma Katha', 3),
 (190, 1950, 'Telugu', 'Raja Vikrama (Dubbed from Kannada)', 3),
 (191, 1950, 'Telugu', 'Shavukaru', 3),
 (192, 1950, 'Telugu', 'Sri Saibaba', 3),
 (193, 1950, 'Telugu', 'Swapna Sundari', 3),
 (194, 1950, 'Telugu', 'Aahuti', 3),
 (195, 1950, 'Telugu', 'Vaali â€“ Sugreeva', 3),
 (196, 1950, 'Telugu', 'Palletoori Pilla', 3),
 (197, 1950, 'Italian', 'Night Taxi', 5),
 (198, 1950, 'Italian', 'The Elusive Twelve', 5),
 (199, 1950, 'Italian', 'Il Bivio', 5),
 (200, 1950, 'Italian', 'The Glass Castle', 5),
 (201, 1950, 'Italian', 'The Knight Has Arrived!', 5),
 (202, 1950, 'Italian', 'Women and Brigands', 5),
 (203, 1950, 'Italian', "The Beggar's Daughter", 5),
 (204, 1950, 'Italian', 'Pugilatori', 5),
 (205, 1950, 'Italian', 'I Falsari', 5),
 (206, 1950, 'Italian', 'Il Piccolo sceriffo', 5),
 (207, 1950, 'Italian', 'La Palla ovale', 5),
 (208, 1950, 'Italian', 'Sambo', 5),
 (209, 1950, 'Italian', 'Peppino e Violetta', 5),
 (210, 1950, 'Italian', 'Toto the Sheik', 5),
 (211, 1950, 'Italian', 'Pact with the Devil', 5),
 (212, 1950, 'Italian', "Ippodromi all'alba", 5),
 (213, 1950, 'Italian', 'Her Favourite Husband', 5),
 (214, 1950, 'Italian', 'The Bread Peddler', 5),
 (215, 1950, 'Italian', 'Faddija â€“ La legge della vendetta', 5),
 (216, 1950, 'Italian', 'Path of Hope', 5),
 (217, 1950, 'Italian', 'Il Richiamo nella tempesta', 5),
 (218, 1950, 'Italian', 'Story of a Love Affair', 5),
 (219, 1950, 'Italian', "L' Amore di Norma", 5),
 (220, 1950, 'Italian', 'Passione fatale', 5),
 (221, 1950, 'Italian', 'Song of Spring', 5),
 (222, 1950, 'Italian', 'Il Mulatto', 5),
 (223, 1950, 'Italian', 'The Transporter', 5),
 (224, 1950, 'Italian', 'The Flowers of St. Francis', 5),
 (225, 1950, 'Italian', 'Lo Zappatore', 5),
 (226, 1950, 'Italian', 'The Cadets of Gascony', 5),
 (227, 1950, 'Italian', 'Variety Lights', 5),
 (228, 1950, 'Italian', 'Beauty and the Devil', 5),
 (229, 1950, 'Italian', 'Behind Closed Shutters', 5),
 (230, 1950, 'Italian', 'Barrier to the North', 5),
 (231, 1950, 'Italian', '1950', 5),
 (232, 1950, 'Italian', 'Nel Mezzogiorno qualcosa Ã¨ cambiata', 5),
 (233, 1950, 'Italian', 'Against the Law', 5),
 (234, 1950, 'Italian', 'Miss Italia', 5),
 (235, 1950, 'Italian', 'Figaro Here, Figaro There', 5),
 (236, 1950, 'Italian', 'Il nido di falasco', 5),
 (237, 1950, 'Italian', 'The Thief of Venice', 5),
 (238, 1950, 'Italian', '47 morto che parla', 5),
 (239, 1950, 'Italian', 'The Count of Saint Elmo', 5),
 (240, 1950, 'Italian', 'The Last Days of Pompeii', 5),
 (241, 1950, 'Italian', "L' Isola bianca", 5),
 (242, 1950, 'Italian', 'The Sky Is Red', 5),
 (243, 1950, 'Italian', 'Il Voto', 5),
 (244, 1950, 'Italian', 'Strano appuntamento', 5),
 (245, 1950, 'Italian', 'Toto Looks for a Wife', 5),
 (246, 1950, 'Italian', 'Cavalcade of Heroes', 5),
 (247, 1950, 'Italian', "I'm in the Revue", 5),
 (248, 1950, 'Italian', 'No Peace Under the Olive Tree', 5),
 (249, 1950, 'Italian', 'Margaret of Cortona', 5),
 (250, 1950, 'Italian', 'Mater dei', 5),
 (251, 1950, 'Italian', 'The Merry Widower', 5),
 (252, 1950, 'Italian', 'Problemi sociali', 5),
 (253, 1950, 'Italian', 'The Paris Waltz', 5),
 (254, 1950, 'Italian', 'Pittori allo specchio', 5),
 (255, 1950, 'Italian', 'The Lion of Amalfi', 5),
 (256, 1950, 'Italian', 'La Strada finisce sul fiume', 5),
 (257, 1950, 'Italian', 'La Villa dei mostri', 5),
 (258, 1950, 'Italian', "It's Forever Springtime", 5),
 (259, 1950, 'Italian', 'Terra senza tempo', 5),
 (260, 1950, 'Italian', "Modena, cittÃ  dell'Emilia Rossa", 5),
 (261, 1950, 'Italian', 'Rapture', 5),
 (262, 1950, 'Italian', "Romanzo d'amore", 5),
 (263, 1950, 'Italian', 'Finestre', 5),
 (264, 1950, 'Italian', 'The Fighting Men', 5),
 (265, 1950, 'Italian', "L' Ospedale del delitto", 5),
 (266, 1950, 'Italian', 'Beauties on Bicycles', 5),
 (267, 1950, 'Italian', 'Turri il bandito', 5),
 (268, 1950, 'Italian', 'Songs in the Streets', 5),
 (269, 1950, 'Italian', 'Napoli milionaria', 5),
 (270, 1950, 'Italian', 'Sunday in August', 5),
 (271, 1950, 'Italian', 'Il Brigante Musolino', 5),
 (272, 1950, 'Italian', "Il Sentiero dell'odio", 5),
 (273, 1950, 'Italian', 'Romanticismo', 5),
 (274, 1950, 'Italian', 'Stromboli', 5),
 (275, 1950, 'Italian', 'Devotion', 5),
 (276, 1950, 'Italian', 'The Two Sisters', 5),
 (277, 1950, 'Italian', 'Tomorrow Is Too Late', 5),
 (278, 1950, 'Italian', 'Volcano', 5),
 (279, 1950, 'Italian', "Bluebeard's Six Wives", 5),
 (280, 1950, 'Italian', "A Dog's Life", 5),
 (281, 1950, 'Italian', 'Due sorelle amano', 5),
 (282, 1950, 'Italian', 'Hearts at Sea', 5),
 (283, 1950, 'Italian', 'The Devil in the Convent', 5),
 (284, 1950, 'Italian', 'That Ghost of My Husband', 5),
 (285, 1950, 'Italian', "La Valle dell'odio", 5),
 (286, 1950, 'Italian', 'Vendetta di zingara', 5),
 (287, 1950, 'Italian', 'TotÃ² Tarzan', 5),
 (288, 1950, 'Italian', 'Welcome, Reverend!', 5),
 (289, 1950, 'Italian', 'La Funivia del faloria', 5),
 (290, 1950, 'Italian', 'Capitan Demonio', 5),
 (291, 1950, 'Italian', 'La Taverna della libertÃ ', 5),
 (292, 1950, 'Italian', 'Alina', 5),
 (293, 1950, 'Italian', "Prima comunione (Father's Dilemma)", 5),
 (294, 1950, 'Italian', 'Women Without Names', 5),
 (295, 1950, 'Italian', 'The Cliff of Sin', 5),
 (296, 1950, 'Italian', 'Red Seal', 5),
 (297, 1950, 'Italian', 'Love and Poison', 5),
 (298, 1950, 'Italian', 'The Gay Swordsman', 5),
 (299, 1950, 'Italian', 'The White Line', 5),
 (300, 1950, 'Italian', 'Angelo tra la folla', 5),
 (301, 1950, 'Brazilian', 'O Pecado de Nina', 7),
 (302, 1950, 'Brazilian', 'Aviso aos Navegantes', 7),
 (303, 1950, 'Brazilian', 'CaiÃ§ara', 7),
 (304, 1950, 'Brazilian', 'Somos Dois', 7),
 (305, 1950, 'Brazilian', 'Todos Por Um', 7),
 (306, 1950, 'Brazilian', 'CaraÃ§a, Porta do CÃ©u', 7),
 (307, 1950, 'Brazilian', 'Estrela da ManhÃ£', 7),
 (308, 1950, 'Brazilian', 'A Sombra da Outra', 7),
 (309, 1950, 'Brazilian', 'A InconveniÃªncia de Ser Esposa', 7),
 (310, 1950, 'Brazilian', 'NÃ£o Ã‰ Nada Disso', 7),
 (311, 1950, 'Brazilian', 'Katucha', 7),
 (312, 1950, 'Brazilian', 'O Noivo de Minha Mulher', 7),
 (313, 1950, 'Brazilian', 'Ã‰charpe de Seda', 7),
 (314, 1950, 'Brazilian', 'Cascalho', 7),
 (315, 1950, 'Brazilian', 'Quando a Noite Acaba', 7),
 (316, 1950, 'Brazilian', 'A Serra da Aventura', 7),
 (317, 1950, 'Brazilian', 'LampiÃ£o, o Rei do CangaÃ§o', 7),
 (318, 1950, 'Brazilian', 'Garota Mineira', 7),
 (319, 1950, 'Brazilian', 'Alameda da Saudade 113', 7),
 (320, 1950, 'Brazilian', 'Um Beijo Roubado', 7),
 (321, 1950, 'Egyptian', 'El Millionair(The Millionaire)', 8),
 (322, 1950, 'Egyptian', 'Shatie el Gharam(Shore of Love)', 8),
 (323, 1950, 'Egyptian', 'Akhlaq Lil Bai(Virtue for Sale)', 8),
 (324, 1950, 'Pakistani', 'Hamari Basti', 9),
 (325, 1950, 'Pakistani', 'Anokhi Dastan', 9),
 (326, 1950, 'Pakistani', 'Amanat', 9),
 (327, 1950, 'Pakistani', 'Jahad', 9),
 (328, 1950, 'Pakistani', 'Gabhroo', 9),
 (329, 1950, 'Pakistani', 'Judai', 9),
 (330, 1950, 'Pakistani', 'Ghalt Fehmi', 9),
 (331, 1950, 'Pakistani', 'Bell', 9),
 (332, 1950, 'Pakistani', 'Beqarar', 9),
 (333, 1950, 'Pakistani', 'Do Ansoo', 9),
 (334, 1950, 'Pakistani', '1950', 9),
 (335, 1950, 'Pakistani', 'Laray', 9),
 (336, 1950, 'Pakistani', 'Kundan', 9),
 (337, 1950, 'Pakistani', 'Shammi', 9),
 (338, 1950, 'Soviet', 'Secret Mission', 10),
 (339, 1950, 'Soviet', 'Cossacks of the Kuban', 10),
 (340, 1950, 'Soviet', 'Far from Moscow', 10),
 (341, 1950, 'Soviet', 'Zhukovsky', 10),
 (342, 1950, 'Soviet', 'Conspiracy of the Doomed', 10),
 (343, 1950, 'Soviet', 'The Lights of Baku', 10),
 (344, 1950, 'Soviet', 'The New China', 10),
 (345, 1950, 'Soviet', 'The Tale of the Fisherman and the Fish', 10),
 (346, 1950, 'Soviet', 'The Fall of Berlin', 10),
 (347, 1950, 'Soviet', 'Brave People', 10),
 (348, 1950, 'Soviet', '1950', 10),
 (349, 1950, 'Soviet', 'Mussorgsky', 10),
 (350, 1950, 'Soviet', 'Dream of a Cossack', 10),
 (351, 1950, 'Japanese', 'An Engagement Ring', 11),
 (352, 1950, 'Japanese', 'Tokyo Kid', 11),
 (353, 1950, 'Japanese', 'Until We Meet Again', 11),
 (354, 1950, 'Japanese', 'The Munekata Sisters', 11),
 (355, 1950, 'Japanese', 'Escape at Dawn', 11),
 (356, 1950, 'Japanese', 'Battle of Roses', 11),
 (357, 1950, 'Japanese', 'Scandal', 11),
 (358, 1950, 'Japanese', 'Portrait of Madame Yuki', 11),
 (359, 1950, 'Japanese', 'Conduct Report on Professor Ishinaka', 11),
 (360, 1950, 'Japanese', 'Rashomon', 11),
 (361, 1950, 'Ollywood', 'Sri Jagannath[2]', 12),
 (362, 1950, 'Ollywood', '1950', 12),
 (363, 1950, 'Ollywood', 'Saptasajya[1]', 12),
 (364, 1950, 'Hong_Kong', 'Wu long jiang jun', 14),
 (365, 1950, 'Hong_Kong', '1950', 14),
 (366, 1950, 'Hong_Kong', 'Monk in Love', 14),
 (367, 1950, 'Hong_Kong', 'The Story of Xiaowan Dong', 14),
 (368,
  1950,
  'Hong_Kong',
  'Emei fei jian xia xia jiThe Flying Sword Hero from Emei Mountain II',
  14),
 (369, 1950, 'Hong_Kong', 'A Chivalrous Bandit', 14),
 (370, 1950, 'Hong_Kong', 'Qian li song ji mao A Small Gift From Afar', 14),
 (371, 1950, 'Hong_Kong', 'Jie hun 24 xiao shi 24 Hours of Marriage', 14),
 (372, 1950, 'Hong_Kong', 'Bird on the Wing (aka Ling xiao gu yan)', 14),
 (373, 1950, 'Hong_Kong', 'The Awful Truth (aka Shuo huang shi jie)', 14),
 (374,
  1950,
  'Hong_Kong',
  'The Abandoned Woman of a Rich Family (aka Hao men qi fu)',
  14),
 (375,
  1950,
  'Hong_Kong',
  'The Battle Between Demon Girl and the Ox Devil',
  14),
 (376, 1950, 'Hong_Kong', 'Xi lu xiang', 14),
 (377, 1950, 'Hong_Kong', 'Zui e suo lian shang ji', 14),
 (378, 1950, 'Hong_Kong', 'Hei tian tang Dark Paradise', 14),
 (379, 1950, 'Hong_Kong', 'Black Market Marriage', 14),
 (380, 1950, 'Hong_Kong', 'Three Girl Musketeers (Nu san jian xia)', 14),
 (381,
  1950,
  'Hong_Kong',
  'The Flower Drops by the Red Chamber (Hua luo hong lou)',
  14),
 (382, 1950, 'Hong_Kong', 'Wild Flowers Are Sweeters', 14),
 (383,
  1950,
  'Hong_Kong',
  'Wan jie qing yuan Loves Caught in 10,000 Perils',
  14),
 (384, 1950, 'Hong_Kong', 'Nian wan qianThe End of the Year Means Money', 14),
 (385, 1950, 'Hong_Kong', 'Jin suo jiThe Golden Chain', 14),
 (386, 1950, 'Hong_Kong', "A White Python Usurps the Dragon's Palace", 14),
 (387, 1950, 'Hong_Kong', 'The Flower Street (Hua jie)', 14),
 (388, 1950, 'Hong_Kong', "Nanhai yu ge The Nanhai Fisherman's Song", 14),
 (389,
  1950,
  'Hong_Kong',
  'Fan gong qing lei Love Tears of a Buddhist Recluse',
  14),
 (390, 1950, 'Hong_Kong', 'The Haunted House', 14),
 (391,
  1950,
  'Hong_Kong',
  'Shen xia jin luo han Magnificent Hero Jin Luohan',
  14),
 (392, 1950, 'Hong_Kong', 'The Flying Sword Hero from Emei Mountain', 14),
 (393, 1950, 'Hong_Kong', 'Zui e suo lian xia ji', 14),
 (394, 1950, 'Hong_Kong', 'Fang Shiyu fu zi bao xie chou', 14),
 (395,
  1950,
  'Hong_Kong',
  "The Flying Swordsman's Bloody Battle at Zhou Village (aka Fei jian xia xie zhan Zhou gu zhuang)",
  14),
 (396, 1950, 'Hong_Kong', 'Blood, Rouge and Tears', 14),
 (397,
  1950,
  'Hong_Kong',
  'Daisen qi an How Inspector Daisen Shattered the Strange Cloaks Gang',
  14),
 (398,
  1950,
  'Hong_Kong',
  "Hua he shang da nao Wutai shan Rude Monk's Intrusion Into Wutai Mountain",
  14),
 (399, 1950, 'Hong_Kong', "Devil's Family", 14),
 (400, 1950, 'Hong_Kong', 'Nan lai yan', 14),
 (401, 1950, 'Hong_Kong', 'Jiang hu qi xiaStrange Hero', 14),
 (402, 1950, 'Hong_Kong', 'The Girl Minstrel (aka Tian ya ge nu)', 14),
 (403, 1950, 'Hong_Kong', 'Magic of Tiger Dragon', 14),
 (404,
  1950,
  'Hong_Kong',
  'Leng luo duan chang hua Sorrows of a Neglected Wife',
  14),
 (405, 1950, 'Hong_Kong', 'Ren hai wan hua tongKaleidoscope', 14),
 (406, 1950, 'Hong_Kong', 'Lust of a Grand Lady', 14),
 (407, 1950, 'Hong_Kong', 'Emei fei jian xiaYi dai yao ji', 14),
 (408, 1950, 'Hong_Kong', 'The Kid (aka Xi lu xiang, Sai lo cheung)', 14),
 (409,
  1950,
  'Hong_Kong',

In [97]:
df = pd.DataFrame(res, columns=["id", "year", "country", "title", "list_id"])
df = df.set_index(["id"])
df["title_clean"] = np.NAN
df["title_bracket"] = np.NAN
df["title_bracket_2"] = np.NAN
df

,year,country,title,list_id,title_clean,title_bracket,title_bracket_2
id,,,,,,,
1,1950,Hindi,Sangram,1,NaN,NaN,NaN
2,1950,Hindi,Raj Mukut,1,NaN,NaN,NaN
3,1950,Hindi,Beqasoor,1,NaN,NaN,NaN
4,1950,Hindi,Hamara Ghar,1,NaN,NaN,NaN
5,1950,Hindi,Gulnar,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...
103643,1979,Turkish,Sona Kalan Dona KalÄ±r,684,NaN,NaN,NaN
103644,1979,Turkish,Bir Ã‡iÃ§ek ÃœÃ§ BÃ¶cek,684,NaN,NaN,NaN
103645,1979,Turkish,MaceranÄ±n BÃ¶ylesi,684,NaN,NaN,NaN
103646,1979,Turkish,Åžark BÃ¼lbÃ¼lÃ¼,684,NaN,NaN,NaN
103647,1979,Turkish,ÃœÃ§ TatlÄ± Bela / Ã–ldÃ¼ren Ã–rÃ¼mcek,684,NaN,NaN,NaN

In [98]:
list(df.columns.values)
df = df [['year', 'country', 'title', 'title_clean', 'title_bracket', 'title_bracket_2', 'list_id']]
df

,year,country,title,title_clean,title_bracket,title_bracket_2,list_id
id,,,,,,,
1,1950,Hindi,Sangram,NaN,NaN,NaN,1
2,1950,Hindi,Raj Mukut,NaN,NaN,NaN,1
3,1950,Hindi,Beqasoor,NaN,NaN,NaN,1
4,1950,Hindi,Hamara Ghar,NaN,NaN,NaN,1
5,1950,Hindi,Gulnar,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...
103643,1979,Turkish,Sona Kalan Dona KalÄ±r,NaN,NaN,NaN,684
103644,1979,Turkish,Bir Ã‡iÃ§ek ÃœÃ§ BÃ¶cek,NaN,NaN,NaN,684
103645,1979,Turkish,MaceranÄ±n BÃ¶ylesi,NaN,NaN,NaN,684
103646,1979,Turkish,Åžark BÃ¼lbÃ¼lÃ¼,NaN,NaN,NaN,684
103647,1979,Turkish,ÃœÃ§ TatlÄ± Bela / Ã–ldÃ¼ren Ã–rÃ¼mcek,NaN,NaN,NaN,684

In [175]:
pattern = '\((.*)\)'
df['title_bracket'] = df['title'].str.findall(pattern)
# find inside bracket
df['title_bracket'] = df['title_bracket'].apply(lambda x: x[0] if x else np.NaN)
# remove first word inside bracket -- some brackets contain (aka [alternative name]) so need to remove the aka
df['title_bracket_2'] = df['title_bracket'].apply(lambda x: re.match(".*? (.*)", str(x)).group(1) if re.match(".*? (.*)", str(x)) else np.NaN)
# get a clean title that does not have brackets
df['title_clean'] = df['title'].apply(lambda x: x if not re.findall("\(", str(x)) else re.match("(.*)\(", str(x)).group(1))
df

,year,country,title,title_clean,title_bracket,title_bracket_2,list_id
id,,,,,,,
1,1950,Hindi,Sangram,Sangram,NaN,NaN,1
2,1950,Hindi,Raj Mukut,Raj Mukut,NaN,NaN,1
3,1950,Hindi,Beqasoor,Beqasoor,NaN,NaN,1
4,1950,Hindi,Hamara Ghar,Hamara Ghar,NaN,NaN,1
5,1950,Hindi,Gulnar,Gulnar,NaN,NaN,1
...,...,...,...,...,...,...,...
103643,1979,Turkish,Sona Kalan Dona KalÄ±r,Sona Kalan Dona KalÄ±r,NaN,NaN,684
103644,1979,Turkish,Bir Ã‡iÃ§ek ÃœÃ§ BÃ¶cek,Bir Ã‡iÃ§ek ÃœÃ§ BÃ¶cek,NaN,NaN,684
103645,1979,Turkish,MaceranÄ±n BÃ¶ylesi,MaceranÄ±n BÃ¶ylesi,NaN,NaN,684
103646,1979,Turkish,Åžark BÃ¼lbÃ¼lÃ¼,Åžark BÃ¼lbÃ¼lÃ¼,NaN,NaN,684
103647,1979,Turkish,ÃœÃ§ TatlÄ± Bela / Ã–ldÃ¼ren Ã–rÃ¼mcek,ÃœÃ§ TatlÄ± Bela / Ã–ldÃ¼ren Ã–rÃ¼mcek,NaN,NaN,684

In [176]:
df[df["title_clean"].str.contains("\[", na=False)]
# some titles have [] brackets that need to be removed
df['title_clean'] = df['title_clean'].apply(lambda x: re.match("(.*)\[", str(x)).group(1) if re.findall("\[", str(x)) else x)
df

,year,country,title,title_clean,title_bracket,title_bracket_2,list_id
id,,,,,,,
1,1950,Hindi,Sangram,Sangram,NaN,NaN,1
2,1950,Hindi,Raj Mukut,Raj Mukut,NaN,NaN,1
3,1950,Hindi,Beqasoor,Beqasoor,NaN,NaN,1
4,1950,Hindi,Hamara Ghar,Hamara Ghar,NaN,NaN,1
5,1950,Hindi,Gulnar,Gulnar,NaN,NaN,1
...,...,...,...,...,...,...,...
103643,1979,Turkish,Sona Kalan Dona KalÄ±r,Sona Kalan Dona KalÄ±r,NaN,NaN,684
103644,1979,Turkish,Bir Ã‡iÃ§ek ÃœÃ§ BÃ¶cek,Bir Ã‡iÃ§ek ÃœÃ§ BÃ¶cek,NaN,NaN,684
103645,1979,Turkish,MaceranÄ±n BÃ¶ylesi,MaceranÄ±n BÃ¶ylesi,NaN,NaN,684
103646,1979,Turkish,Åžark BÃ¼lbÃ¼lÃ¼,Åžark BÃ¼lbÃ¼lÃ¼,NaN,NaN,684
103647,1979,Turkish,ÃœÃ§ TatlÄ± Bela / Ã–ldÃ¼ren Ã–rÃ¼mcek,ÃœÃ§ TatlÄ± Bela / Ã–ldÃ¼ren Ã–rÃ¼mcek,NaN,NaN,684

In [179]:
df.to_sql('movie_titles_cleaned', con=con, if_exists='append')

103327